### ISSUE TITLE
'DataFrame' object has no attribute 'RentalDry'

### ISSUE THREAD

**Issue by maletin** [BlackCelebrant/FSEconomy#13]
```bash
$ python main.py --ukey=*** --local
/home/maletin/git/github/FSEconomy/fseconomy.py:37: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  return aggregated.sort('Pay', ascending=False)
Searching for the best aircraft from NGTA
--Searching for the best aircraft from NGTA
Traceback (most recent call last):
  File "main.py", line 79, in <module>
    main()
  File "main.py", line 75, in main
    do_work(args)
  File "main.py", line 27, in do_work
    best_aircraft = fse.get_best_craft(row['FromIcao'], args.radius)
  File "/home/maletin/git/github/FSEconomy/fseconomy.py", line 81, in get_best_craft
    aircrafts = self.get_aircrafts_by_icao(near_icao)
  File "/home/maletin/git/github/FSEconomy/fseconomy.py", line 42, in get_aircrafts_by_icao
    aircrafts.RentalDry = aircrafts.RentalDry.astype(float)
  File "/home/maletin/git/github/FSEconomy/.venv/local/lib/python2.7/site-packages/pandas/core/generic.py", line 2744, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'RentalDry'
```

**Comment by BlackCelebrant** [comment]
I missed the issue because I used a service key for all operations. Since user key is less loyal for frequent queries, I changed retry logic. Each time server returns a error - script will pause for 60 seconds.
